### ISSUE TITLE
Hearing Your Future recording checklist and workflow

### ISSUE THREAD

**Issue by dullhunk** [dullhunk/cdyf#822]
# Before

- [ ] ask which questions they'd like to opt out of
- [ ] speak freely, guest has final say
- [ ] google recorder for transcript
- [ ] set correct microphone for input in GarageBand settings

# After

- [ ] studio selfie
- [ ] social media permissions
- [ ] profile picture

# GarageBand Gubbins

- [ ] top
- [ ] tail
- [ ] export `Share > Export song to disk`
- [ ] fill in form at https://five.libsyn.com/show/episodes/add
- [ ] remove episode number for Apple (or not?)
